language: csharp
mono: none
#match on https://www.microsoft.com/net/download/linux
dotnet: 1.0.3
sudo: required
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - curl

script:
  - which dotnet
  - dotnet --info
  - dotnet restore
  - pushd src/CoreDocker.Api && dotnet restore  && dotnet build
  - popd
  - pushd test/CoreDocker.Core.Tests && dotnet test 
  - popd
  #- pushd test/CoreDocker.Sdk.Tests && dotnet test 
  #- popd
  - pushd test/CoreDocker.Utilities.Tests && dotnet test 
  - popd
  - pushd test/CoreDocker.Dal.Tests && dotnet test 
  - popd

after_success:
  # Add docker images
  - pushd src/ 
  - docker pull microsoft/dotnet
  - dotnet restore
  - pushd CoreDocker.Api
  - dotnet publish   --version-suffix $TRAVIS_BUILD_NUMBER -c Debug -o bin/publish
  - popd
  - docker build -t rolfwessels/coredocker:latest -t rolfwessels/coredocker:v0.0.$TRAVIS_BUILD_NUMBER .
  - popd
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push rolfwessels/coredocker;
    fi